export const EXTRA_ITEMS = {
  fig: {
    name: "Figo",
    description: "Recupera 16 de saciedade. Perecível: acompanhe o frescor.",
    icon: "fig",
    category: "Suprimentos",
  },
  guava: {
    name: "Goiaba",
    description: "Recupera 22 de saciedade. Perecível: acompanhe o frescor.",
    icon: "guava",
    category: "Suprimentos",
  },
  avocado: {
    name: "Abacate",
    description: "Recupera 30 de saciedade. Perecível: acompanhe o frescor.",
    icon: "avocado",
    category: "Suprimentos",
  },
  banana: {
    name: "Banana",
    description: "Recupera 22 de saciedade. Perecível: acompanhe o frescor.",
    icon: "banana",
    category: "Suprimentos",
  },
  chocolate: {
    name: "Chocolate",
    description: "Recupera 26 de saciedade. Embalado para durar.",
    icon: "chocolate",
    category: "Suprimentos",
  },
  potato: {
    name: "Batata crua",
    description: "Precisa ser cozido em uma fogueira ou fogão.",
    icon: "potato",
    category: "Suprimentos",
  },
  rawMeat: {
    name: "Carne crua",
    description: "Precisa ser cozido em uma fogueira ou fogão.",
    icon: "rawMeat",
    category: "Suprimentos",
  },
  cookedMeat: {
    name: "Carne assada",
    description: "Recupera 45 de saciedade. Perecível: acompanhe o frescor.",
    icon: "cookedMeat",
    category: "Suprimentos",
  },
  carrot: {
    name: "Cenoura",
    description: "Recupera 16 de saciedade. Perecível: acompanhe o frescor.",
    icon: "carrot",
    category: "Suprimentos",
  },
  greenApple: {
    name: "Maçã verde",
    description: "Recupera 20 de saciedade. Perecível: acompanhe o frescor.",
    icon: "greenApple",
    category: "Suprimentos",
  },
  kiwi: {
    name: "Kiwi",
    description: "Recupera 16 de saciedade. Perecível: acompanhe o frescor.",
    icon: "kiwi",
    category: "Suprimentos",
  },
  rice: {
    name: "Arroz enlatado",
    description: "Recupera 34 de saciedade. Embalado para durar.",
    icon: "rice",
    category: "Suprimentos",
  },
  beans: {
    name: "Feijão enlatado",
    description: "Recupera 36 de saciedade. Embalado para durar.",
    icon: "beans",
    category: "Suprimentos",
  },
  lemon: {
    name: "Limão",
    description: "Recupera 10 de saciedade. Perecível: acompanhe o frescor.",
    icon: "lemon",
    category: "Suprimentos",
  },
  pasta: {
    name: "Macarrão enlatado",
    description: "Recupera 35 de saciedade. Embalado para durar.",
    icon: "pasta",
    category: "Suprimentos",
  },
  onion: {
    name: "Cebola",
    description: "Recupera 10 de saciedade. Perecível: acompanhe o frescor.",
    icon: "onion",
    category: "Suprimentos",
  },
  orange: {
    name: "Laranja",
    description: "Recupera 20 de saciedade. Perecível: acompanhe o frescor.",
    icon: "orange",
    category: "Suprimentos",
  },
  bread: {
    name: "Pão",
    description: "Recupera 25 de saciedade. Perecível: acompanhe o frescor.",
    icon: "bread",
    category: "Suprimentos",
  },
  papaya: {
    name: "Mamão",
    description: "Recupera 30 de saciedade. Perecível: acompanhe o frescor.",
    icon: "papaya",
    category: "Suprimentos",
  },
  passionFruit: {
    name: "Maracujá",
    description: "Recupera 18 de saciedade. Perecível: acompanhe o frescor.",
    icon: "passionFruit",
    category: "Suprimentos",
  },
  purplePassionFruit: {
    name: "Maracujá roxo",
    description: "Recupera 18 de saciedade. Perecível: acompanhe o frescor.",
    icon: "purplePassionFruit",
    category: "Suprimentos",
  },
  peach: {
    name: "Pêssego",
    description: "Recupera 20 de saciedade. Perecível: acompanhe o frescor.",
    icon: "peach",
    category: "Suprimentos",
  },
  pear: {
    name: "Pera",
    description: "Recupera 20 de saciedade. Perecível: acompanhe o frescor.",
    icon: "pear",
    category: "Suprimentos",
  },
  pineapple: {
    name: "Abacaxi",
    description: "Recupera 35 de saciedade. Perecível: acompanhe o frescor.",
    icon: "pineapple",
    category: "Suprimentos",
  },
  sicilianLemon: {
    name: "Limão siciliano",
    description: "Recupera 12 de saciedade. Perecível: acompanhe o frescor.",
    icon: "sicilianLemon",
    category: "Suprimentos",
  },
  starfruit: {
    name: "Carambola",
    description: "Recupera 18 de saciedade. Perecível: acompanhe o frescor.",
    icon: "starfruit",
    category: "Suprimentos",
  },
  juice: {
    name: "Suco",
    description: "Recupera 12 de saciedade. Embalado para durar.",
    icon: "juice",
    category: "Suprimentos",
  },
  yellowPear: {
    name: "Pera amarela",
    description: "Recupera 20 de saciedade. Perecível: acompanhe o frescor.",
    icon: "yellowPear",
    category: "Suprimentos",
  },
  bakedPotato: {
    name: "Batata assada",
    description: "Recupera 32 de saciedade. Perecível: acompanhe o frescor.",
    icon: "bakedPotato",
    category: "Suprimentos",
  },
  battery: {
    name: "Bateria",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "battery",
    category: "Materiais",
  },
  vest: {
    name: "Colete",
    description: "Equipar: proteção de 50%.",
    icon: "vest",
    category: "Equipamento",
  },
  wire: {
    name: "Fios",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "wire",
    category: "Materiais",
  },
  gasMask: {
    name: "Máscara de gás",
    description: "Equipar: reduz a contaminação da zona radioativa em 85%.",
    icon: "gasMask",
    category: "Equipamento",
  },
  fuel: {
    name: "Combustível",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "fuel",
    category: "Materiais",
  },
  grenade: {
    name: "Granada",
    description: "Usar: arremessa uma granada na direção da mira.",
    icon: "grenade",
    category: "Equipamento",
  },
  lighter: {
    name: "Isqueiro",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "lighter",
    category: "Materiais",
  },
  mask: {
    name: "Máscara",
    description: "Equipar: reduz a contaminação da zona radioativa em 50%.",
    icon: "mask",
    category: "Equipamento",
  },
  matches: {
    name: "Fósforos",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "matches",
    category: "Materiais",
  },
  nightVision: {
    name: "Visor noturno",
    description: "Equipar: amplia a visão noturna. Requer uma bateria.",
    icon: "nightVision",
    category: "Equipamento",
  },
  leather: {
    name: "Couro",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "leather",
    category: "Materiais",
  },
  nails: {
    name: "Pregos",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "nails",
    category: "Materiais",
  },
  rope: {
    name: "Corda",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "rope",
    category: "Materiais",
  },
  smoke: {
    name: "Sinalizador de fumaça",
    description: "Usar: mascara sua posição por alguns segundos.",
    icon: "smoke",
    category: "Equipamento",
  },
  note: {
    name: "Anotação",
    description: "Use para ler uma nota de sobrevivência.",
    icon: "note",
    category: "Equipamento",
  },
  tape: {
    name: "Fita adesiva",
    description:
      "Material para fabricar equipamentos, combustível ou manutenção.",
    icon: "tape",
    category: "Materiais",
  },
  musicRadio: {
    name: "Rádio portátil",
    description: "Use para alternar a trilha sonora.",
    icon: "musicRadio",
    category: "Equipamento",
  },
  crowbar: {
    name: "Pé de cabra",
    description: "Abre portas reforçadas de casas com suprimentos melhores.",
    icon: "crowbar",
    category: "Equipamento",
  },
} as const;
export const NUTRITION: Record<
  string,
  {
    hunger: number;
    thirst: number;
    lifetime: number;
    raw: boolean;
  }
> = {
  fig: {
    hunger: 16,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  guava: {
    hunger: 22,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  avocado: {
    hunger: 30,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  banana: {
    hunger: 22,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  chocolate: {
    hunger: 26,
    thirst: 0,
    lifetime: 0,
    raw: false,
  },
  potato: {
    hunger: 0,
    thirst: 0,
    lifetime: 480,
    raw: true,
  },
  rawMeat: {
    hunger: 0,
    thirst: 0,
    lifetime: 360,
    raw: true,
  },
  cookedMeat: {
    hunger: 45,
    thirst: 0,
    lifetime: 720,
    raw: false,
  },
  carrot: {
    hunger: 16,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  greenApple: {
    hunger: 20,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  kiwi: {
    hunger: 16,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  rice: {
    hunger: 34,
    thirst: 0,
    lifetime: 0,
    raw: false,
  },
  beans: {
    hunger: 36,
    thirst: 0,
    lifetime: 0,
    raw: false,
  },
  lemon: {
    hunger: 10,
    thirst: 6,
    lifetime: 480,
    raw: false,
  },
  pasta: {
    hunger: 35,
    thirst: 0,
    lifetime: 0,
    raw: false,
  },
  onion: {
    hunger: 10,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  orange: {
    hunger: 20,
    thirst: 6,
    lifetime: 480,
    raw: false,
  },
  bread: {
    hunger: 25,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  papaya: {
    hunger: 30,
    thirst: 6,
    lifetime: 480,
    raw: false,
  },
  passionFruit: {
    hunger: 18,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  purplePassionFruit: {
    hunger: 18,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  peach: {
    hunger: 20,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  pear: {
    hunger: 20,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  pineapple: {
    hunger: 35,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  sicilianLemon: {
    hunger: 12,
    thirst: 6,
    lifetime: 480,
    raw: false,
  },
  starfruit: {
    hunger: 18,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  juice: {
    hunger: 12,
    thirst: 30,
    lifetime: 0,
    raw: false,
  },
  yellowPear: {
    hunger: 20,
    thirst: 0,
    lifetime: 480,
    raw: false,
  },
  bakedPotato: {
    hunger: 32,
    thirst: 0,
    lifetime: 720,
    raw: false,
  },
};
export const EXTRA_PHYSICS = {
  fig: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  guava: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  avocado: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  banana: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  chocolate: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  potato: {
    weight: 0.4,
    w: 1,
    h: 1,
    stack: 3,
  },
  rawMeat: {
    weight: 0.4,
    w: 2,
    h: 1,
    stack: 3,
  },
  cookedMeat: {
    weight: 0.25,
    w: 2,
    h: 1,
    stack: 3,
  },
  carrot: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  greenApple: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  kiwi: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  rice: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  beans: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  lemon: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  pasta: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  onion: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  orange: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  bread: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  papaya: {
    weight: 0.9,
    w: 1,
    h: 1,
    stack: 3,
  },
  passionFruit: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  purplePassionFruit: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  peach: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  pear: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  pineapple: {
    weight: 0.9,
    w: 2,
    h: 2,
    stack: 3,
  },
  sicilianLemon: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  starfruit: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  juice: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  yellowPear: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  bakedPotato: {
    weight: 0.25,
    w: 1,
    h: 1,
    stack: 3,
  },
  battery: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  vest: {
    weight: 2.5,
    w: 2,
    h: 3,
    stack: 1,
  },
  wire: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  gasMask: {
    weight: 0.15,
    w: 2,
    h: 1,
    stack: 1,
  },
  fuel: {
    weight: 2,
    w: 2,
    h: 3,
    stack: 4,
  },
  grenade: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  lighter: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 1,
  },
  mask: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  matches: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  nightVision: {
    weight: 0.15,
    w: 2,
    h: 1,
    stack: 1,
  },
  leather: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  nails: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  rope: {
    weight: 0.6,
    w: 1,
    h: 1,
    stack: 4,
  },
  smoke: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  note: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  tape: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 4,
  },
  musicRadio: {
    weight: 0.15,
    w: 1,
    h: 1,
    stack: 1,
  },
  crowbar: {
    weight: 2.2,
    w: 1,
    h: 3,
    stack: 1,
  },
};
export const SUPPLY_IMAGES = {
  fig: "assets/Itens/Foods/1.png",
  guava: "assets/Itens/Foods/26.png",
  avocado: "assets/Itens/Foods/avocado.png",
  banana: "assets/Itens/Foods/banana.png",
  chocolate: "assets/Itens/Foods/barra-chocolate.png",
  potato: "assets/Itens/Foods/batata.png",
  rawMeat: "assets/Itens/Foods/carne-crua.png",
  cookedMeat: "assets/Itens/Foods/carne.png",
  carrot: "assets/Itens/Foods/cenoura.png",
  greenApple: "assets/Itens/Foods/green-apple.png",
  kiwi: "assets/Itens/Foods/kiwi.png",
  rice: "assets/Itens/Foods/lata-arroz.png",
  beans: "assets/Itens/Foods/lata-feijao.png",
  lemon: "assets/Itens/Foods/lemon.png",
  pasta: "assets/Itens/Foods/marcarro-enlatado.png",
  onion: "assets/Itens/Foods/onion.png",
  orange: "assets/Itens/Foods/orange.png",
  bread: "assets/Itens/Foods/pao.png",
  papaya: "assets/Itens/Foods/papaya.png",
  passionFruit: "assets/Itens/Foods/passion_fruit.png",
  purplePassionFruit: "assets/Itens/Foods/passion_fruit_purple.png",
  peach: "assets/Itens/Foods/peach.png",
  pear: "assets/Itens/Foods/pear.png",
  pineapple: "assets/Itens/Foods/pineapple.png",
  sicilianLemon: "assets/Itens/Foods/sicilian-lemon.png",
  starfruit: "assets/Itens/Foods/starfruit.png",
  juice: "assets/Itens/Foods/suco.png",
  yellowPear: "assets/Itens/Foods/yellow-pear.png",
  bakedPotato: "assets/Itens/Foods/batata.png",
  battery: "assets/Itens/Variable/bateria.png",
  vest: "assets/Itens/Variable/colete.png",
  wire: "assets/Itens/Variable/fios.png",
  gasMask: "assets/Itens/Variable/gas-mask.png",
  fuel: "assets/Itens/Variable/gasoline.png",
  grenade: "assets/Itens/Variable/granada.png",
  lighter: "assets/Itens/Variable/lighter.png",
  mask: "assets/Itens/Variable/mask.png",
  matches: "assets/Itens/Variable/match.png",
  nightVision: "assets/Itens/Variable/nightvision.png",
  leather: "assets/Itens/Variable/pele-animal.png",
  nails: "assets/Itens/Variable/pregos.png",
  rope: "assets/Itens/Variable/rope.png",
  smoke: "assets/Itens/Variable/smoke.png",
  note: "assets/Itens/Variable/anotacao.png",
  tape: "assets/Itens/Variable/83.png",
  musicRadio: "assets/Itens/Variable/radio-musica.png",
  crowbar: "assets/Itens/Variable/crowbar.png",
};
